# Generated by Django 2.1.4 on 2018-12-05 23:08

from django.db import migrations, models
import edison.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('grade', edison.models.IntegerRangeField()),
                ('address', models.CharField(max_length=100)),
                ('Pass_code', models.CharField(max_length=13)),
            ],
        ),
    ]
