# Generated by Django 2.1.4 on 2018-12-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edison', '0002_auto_20181206_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
