# Generated by Django 2.1.4 on 2018-12-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edison', '0003_auto_20181206_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
