# Generated by Django 2.1.4 on 2018-12-12 23:38

from django.db import migrations, models
import edison.models


class Migration(migrations.Migration):

    dependencies = [
        ('edison', '0004_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_code', models.CharField(max_length=20)),
                ('Subject_name', models.CharField(max_length=50)),
                ('Subject_points', edison.models.IntegerRangeField()),
                ('Subject_pass', models.IntegerField(choices=[(1, 'Examination'), (2, 'Creadit'), (3, 'Dogovorims9')])),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
    ]
